export const smugWinEmoji = ["😎", "😏", "😤", "😌", "😁", "😈", "😬", "😉", "😝", "😼"];
export const smugLossEmoji = ["😞", "😕", "😔", "😢", "😭", "😩", "😓", "😖", "😿", "😣"];
export const faceEmojis = [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "😂",
    "🤣",
    "😊",
    "😇",
    "🙂",
    "🙃",
    "😉",
    "😌",
    "😍",
    "🥰",
    "😘",
    "😗",
    "😙",
    "😚",
    "😋",
    "😛",
    "😝",
    "😜",
    "🤪",
    "🤨",
    "🧐",
    "🤓",
    "😎",
    "🥸",
    "🤩",
    "🥳",
    "😏",
    "😒",
    "😞",
    "😔",
    "😟",
    "😕",
    "🙁",
    "☹️",
    "😣",
    "😖",
    "😫",
    "😩",
    "🥺",
    "😢",
    "😭",
    "😤",
    "😠",
    "😡",
    "🤬",
    "🤯",
    "😳",
    "🥵",
    "🥶",
    "😱",
    "😨",
    "😰",
    "😥",
    "😓",
    "🤗",
    "🤔",
    "🤭",
    "🤫",
    "🤥",
    "😶",
    "😐",
    "😑",
    "😬",
    "🙄",
    "😯",
    "😦",
    "😧",
    "😮",
    "😲",
    "🥱",
    "😴",
    "🤤",
    "😪",
    "😵",
    "🤐",
    "🥴",
    "🤢",
    "🤮",
    "🤧",
    "😷",
    "🤒",
    "🤕",
    "🤑",
];

export const smugWinPhrases = [
    "Too easy.",
    "GG, but not really.",
    "Try harder next time.",
    "Outplayed.",
    "Didn't break a sweat.",
    "You never had a chance.",
    "Is that all you've got?",
    "Flawless.",
    "Predictable.",
    "I do this in my sleep."
];

export const smugLosePhrases = [
    "Come on, that one does't count.",
    "That was a fluke.",
    "I was distracted.",
    "You just got Lucky.",
    "You won't win next time.",
    "Whatever...",
    "Just warming up.",
    "I let you win.",
];

export const drawEndPhrases = [
    ["A tie? Boring.", "😒"],
    ["Guess we’re evenly matched… for now.", "😏"],
    ["You’re lucky I blinked.", "😌"],
    ["Fine, you held up better than I thought.", "😐"],
    ["A draw? How anticlimactic.", "😑"],
    ["You escaped… barely.", "😤"],
    ["Not bad… not great either.", "😬"],
    ["We call that mutual disappointment.", "😑"],
];

export const nextBattleAfterWin = [
    ["Want another beating?", "😎"],
    ["Didn’t get enough?", "😏"],
    ["Still feel lucky?", "😌"],
    ["Rematch? Bold move.", "😈"],
    ["Let’s do it again same result.", "😤"],
    ["I hope you've improved… a little.", "😉"],
    ["Think you can handle round two?", "😝"],
    ["Brace yourself. Again.", "😏"]
];

export const nextBattleAfterLoss = [
    ["That was a warm-up.", "😤"],
    ["Next one’s mine.", "😠"],
    ["I was holding back.", "😏"],
    ["Let’s see you do that twice.", "😒"],
    ["Just wait…", "😑"],
    ["Now I’m actually trying.", "😬"],
    ["Don’t get cocky.", "😐"],
    ["You got lucky, once.", "😕"],
    ["Revenge time.", "😈"],
    ["Let’s settle this properly.", "😎"]
];

export const nextBattleAfterDraw = [
    ["One more. Let’s settle this.", "😠"],
    ["Still think you can keep up?", "😏"],
    ["Let’s break the tie.", "😤"],
    ["This time, no mercy.", "😈"],
    ["No more draws just defeat.", "😎"],
    ["You won't be so lucky again.", "😒"],
    ["Let’s end this properly.", "😌"],
    ["This round, I go all in.", "😬"],
    ["Time for a real winner.", "😆"]
];

export const randomFrom = (arr) => arr[Math.floor(Math.random() * arr.length)];